### ISSUE TITLE
[BUG]Random freeze for few seconds.

### ISSUE THREAD

**Issue by ankushmalik11201** [ananjaser1211/hadesRom_Reports#35] opened 2021-01-04 12:32 UTC
**Describe the bug**
Sometimes when exiting a app (going to home screen), the mobile randomly freezes. It happens with random apps. No physical button works and no touch button works either. It stays freezed for 1-3 seconds. 

**To Reproduce**
It is random so no steps to reproduce.

**Expected behavior**
Not freeze.

**Screenshots**
Not possible to take screenshot when freezed

**Smartphone (please complete the following information):**
 - Device: S8+
 - Model: G955F

**Additional context**
Log report: https://filebin.ca/5n5bWqjdPlHU

It starts at 1-04 17:23 in log. I was exiting Firefox beta then.

**Comment by ankushmalik11201** [comment] 2021-01-04 12:34
Forget to mention I'm rooted but have no modules installed. Only have two apps using root: logcat and HKtweak manager. No bloatware (bixby not installed and set to screenshot)

**Comment by rostifaner** [comment] 2021-01-04 15:12
I can confirm this bug.

**Comment by ananjaser1211** [comment] 2021-01-04 15:22
Duplicate of #17 please move discussion and logs there

**Closed as completed** 2021-01-04 15:22 UTC
