### ISSUE TITLE
[BUG] Front camera face recognition "vibrates"

### ISSUE THREAD

**Issue by daav-dd** [ananjaser1211/hadesRom_Reports#56] opened 2021-01-10 17:09 UTC
**Describe the bug**
The problem is that when you open the camera app and go to the selfie mode, you'll se that the square that recognizes the face, kinda "vibrates".
On the video attached below I used the Di Caprio's face just for privacy reasons but I assure you it happens even with my real face.

**To Reproduce**
1. Go to the camera app
2. Go in selfie mode
3. The square vibrates

**Expected behavior**
Just the normal thing

**Video**
https://user-images.githubusercontent.com/62658015/104130066-00831d00-536f-11eb-8f33-cd86e281ba11.mp4

**Smartphone:**
 - Device: Galaxy S8
 - Model: G950F

**Comment by ananjaser1211** [comment] 2021-09-15 21:35
This has been resolved on my end, but some testers reported it still vibrates, it might be related to cleanflash, report if the bug continues to happen

**Comment by ananjaser1211** [comment] 2021-09-16 05:26
bleh, this seems to only be fixed on my device. broken for everyone else.

**Comment by ananjaser1211** [comment] 2021-09-16 09:58
Thanks to @Drew071 he figured out the issue is due to "Selfie Face Correction" Disable it in the camera settings and the flickering will be gone.

I dont know much about this feature weather it was there in stock or not, so will investigate it further later

![image](https://user-images.githubusercontent.com/25624482/133592291-f867bc55-c1a5-4afe-938a-11f6193f92d3.png)

**Comment by ananjaser1211** [comment] 2021-09-18 00:34
v2.1 will come with this fixed, no workaround needed.

**Comment by ananjaser1211** [comment] 2022-02-05 17:59
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details

**Closed as completed by ananjaser1211** 2022-02-05 17:59 UTC
Labels: addressed
