### ISSUE TITLE
Volume limited for audio [BUG]

### ISSUE THREAD

**Issue by anouar141** [ananjaser1211/hadesRom_Reports#111] opened 2021-09-28 12:36 UTC
Volume slider not working right, I think there's a limitaion for media audio or something like that. because every time i try to rise the  audio to 100% it statys at 50 or 60 %

 - Device: [e.g. Galaxy S8+]
 - Model: [e.g. G955F]

**Comment by ananjaser1211** [comment] 2021-09-29 02:57
Duplicate of #106 

workaround there.

**Closed as completed by ananjaser1211** 2021-09-29 02:57 UTC
