### ISSUE TITLE
[BUG] call audio bluetooth

### ISSUE THREAD

**Issue by Niels7801** [ananjaser1211/hadesRom_Reports#74] opened 2021-02-19 16:15 UTC
When connecting Bluetooth headset (or my galaxy watch) the call audio gets disturbed and cracking (voice is some sort of computer voice totally incomprehensible). While playing music no issues but I cannot call with my watch or bt headset. Tried with wired headset and no issues. Tried with all my other bt headsets and all have this issue (also my car stereo)
Tried to factory reset and issue remains, even with no apps installed.

my phone is a dual sim Note 8 (N950FD)

which logs do you need?
Thanks in advance!

Best regards,
Niels

**Comment by Niels7801** [comment] 2021-02-19 16:21
![Screenshot_20210219-172052](https://user-images.githubusercontent.com/79325705/108531391-eece5700-72d6-11eb-8fe8-a0965bfc7716.jpg)

**Comment by ananjaser1211** [comment] 2021-02-19 18:41
Duplicate of #13 you can move discussion there

**Closed as completed by ananjaser1211** 2021-02-19 18:41 UTC
