### ISSUE TITLE
[BUG]High battery consumption

### ISSUE THREAD

**Issue by ThomasXDA** [ananjaser1211/hadesRom_Reports#39] opened 2021-01-04 17:53 UTC
- Device: [e.g. Galaxy Note8]
 - Model: [e.g. G950F]
**Screenshots**
![Screenshot_20210104-143614_Device care](https://user-images.githubusercontent.com/76965762/103563775-9ed83400-4ed2-11eb-887f-498050533e7d.jpg)
) when applicable
Its not normal.pls fix it

**Comment by corsicanu** [comment] 2021-01-04 17:55
Duplicate of #28

**Closed as completed by corsicanu** 2021-01-04 17:55 UTC
