### ISSUE TITLE
[BUG] Bluetooth doesn't turn on until reboot

### ISSUE THREAD

**Issue by TheXAHTEP** [ananjaser1211/hadesRom_Reports#11] opened 2020-12-27 18:55 UTC
After reboot its on.

https://user-images.githubusercontent.com/25569843/103177495-13382500-488c-11eb-998a-dd881e30b2e3.mp4

 - Device: Galaxy Note 8
 - Model: N950F

Magisk 20.4 installed. Maybe this caused by sync of bluetooth settings by samsung cloud. I tried to clear Bluetooth apk data, but nothing changed.

Error Log File:
[log_e.log](https://github.com/ananjaser1211/hadesRom_Reports/files/5745027/log_e.log)

**Comment by corsicanu** [comment] 2020-12-27 19:38
Cannot reproduce it on my S8 or Note8, i suggest you try doing a network settings reset and see again.
Waiting for feedback.

**Comment by TheXAHTEP** [comment] 2020-12-27 20:24
Network settings reset doesn't work. Flash rom without wipe Data didn't help either. Now I try to flash with full wipe.

**Comment by TheXAHTEP** [comment] 2020-12-27 20:39
Full wipe worked. Idk how lol. I think that my suggestion about samsung cloud is right. Thanks.

**Comment by TheXAHTEP** [comment] 2020-12-28 18:19
I found that problem appears when device search in security settings activated and device search app (com.samsung.android.fmm) on galaxy store gets updated. After deleting update problem disappears. Update without getting that bluetooth problem can be done when device search in security settings deactivated. 

Proof


https://user-images.githubusercontent.com/25569843/103234810-a38c6d80-4951-11eb-8308-f1f3ea6fc7c9.mp4


I'm not sure if this problem is related to samsung account or rom, but I report it just in case.

**Comment by corsicanu** [comment] 2020-12-28 18:54
https://user-images.githubusercontent.com/6254131/103236908-d2edab00-494e-11eb-887b-1f96633da77b.mp4

i tried to update all the apps as you said and still couldn't brick bluetooth. What am i doing wrong here?

**Comment by ananjaser1211** [comment] 2020-12-28 18:57
FMM ( Samsung's find my mobile) should not have any issues with bluetooth. , the app is up-to-date, bluetooth still works fine on my note8

not sure whats going on on your end, maybe check your samsung account settings, maybe you did reactivation lock or something ? not sure tbh.. testers dont have the issue either with updated apps

**Comment by TheXAHTEP** [comment] 2020-12-28 19:31
I didn't even accept a legal agreement in FMM. I never did a FRP bypass or smth. What i did: clean install rom > setup wifi > login into my google and samsung account (login into samsung acc using google) > setup fingerprint > update apps and problem appears. Honestly, idc about FMM and I dont use it anyway (as I said I didn't even accept a legal agreement LOL). I think that problem may appear on a new samsung acc idk. As I deactivate FMM in settings, I can update it without any issue.

**Comment by corsicanu** [comment] 2021-01-02 09:41
I'm really considering closing this issue, i just did a full wipe of my Note8, transferred all the content from S20 to Note8 with SmartSwitch, set everything up, updated all apps and bluetooth is still working.

**Comment by ananjaser1211** [comment] 2021-01-02 14:14
I also have not heard any other users complain about it, so until that happens, it remains isolated and closed

**Closed as completed by ananjaser1211** 2021-01-02 14:14 UTC
Labels: bug, isolated
