### ISSUE TITLE
[BUG] the bluetooth sometimes does not turn on and I have to restart my s8

### ISSUE THREAD

**Issue by jesuspolini** [ananjaser1211/hadesRom_Reports#33] opened 2021-01-03 16:37 UTC
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: S8
 - Model: G950F

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/ananjaser1211/hadesRom_Reports/releases/tag/v3.0) when applicable

**Comment by corsicanu** [comment] 2021-01-03 16:51
Duplicate of #11.
Closing it as we cannot reproduce it after severat tryouts.

**Closed as completed by corsicanu** 2021-01-03 16:51 UTC
