### ISSUE TITLE
[BUG] Clock timer tab is in chinese

### ISSUE THREAD

**Issue by Snowers96** [ananjaser1211/hadesRom_Reports#69] opened 2021-02-09 02:52 UTC
Describe the bug
My system is in English, but my clock timer tab is in Chinese

To Reproduce

Enter stock Clock app, go to the Timer tab and see it

Smartphone:

Device: Galaxy S8 
Model: G950FD

**Comment by corsicanu** [comment] 2021-09-15 22:51
Not a bug tho, so imma close this. We inherit this because of enabling some chinese related features via csc. Since clock is an app which gets self updated from stores we can't mod it to remove the csc checks. The simplest solution is to remove by hand predefined timers.

**Closed as completed by corsicanu** 2021-09-15 22:51 UTC
Labels: bug
