### ISSUE TITLE
[BUG]Phonepe app not working only on this rom.

### ISSUE THREAD

**Issue by ankushmalik11201** [ananjaser1211/hadesRom_Reports#67] opened 2021-02-02 14:13 UTC
**Describe the bug**
I use an app called "Phonepe" for payment. However ever since installing this ROM I can't activate it as it shows "Something went wrong error".  Now i have tried everything from using mobile internet / vpn to different mobile number but it still fails. I even tried magisk hide. This app used to work great before on different custom rom with root (no magisk hiding etc).

I used logcat to find Errors and it seems the app is for some reason unable to get DNS? or its internet check is failing.

**To Reproduce**
1. Open app
2. Enter any random number
3. It will show something went wrong error.

**Expected behavior**
The app proceeds and an otp is generated.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: S8+
 - Model: G955F

**Additional context**
Attached
[Log_2021-01-17_18-08-06.txt](https://github.com/ananjaser1211/hadesRom_Reports/files/5911665/Log_2021-01-17_18-08-06.txt)

**Comment by ananjaser1211** [comment] 2021-02-02 14:16
Android Q has a service that exposes root / magisk to apps that need Safetynet, we will disable this in V2 however there is no guarantee that your app will work. google is enforcing safetynet, and magisk no longer prioritizes hide. nothing more we can do ROM wise

**Comment by ankushmalik11201** [comment] 2021-02-02 14:38
Hey, Thanks for this quick reply however from the log it seems the issue is not of safetynet. Maybe i'm wrong, will see if removing root helps.

**Comment by ankushmalik11201** [comment] 2021-02-02 14:41
Another thing, I accidentally attached the wrong log file. Please check one below. 

Sorry for wrong log.
[Log_2021-02-02_19-32-44.txt](https://github.com/ananjaser1211/hadesRom_Reports/files/5911900/Log_2021-02-02_19-32-44.txt)

**Comment by ananjaser1211** [comment] 2021-02-07 06:53
ive had time to check this, and i cant really see much info about phonepe, app just exists. being a bank app, safetynet is likely the cause

ive tried this app on my S9 with OneUI R and the app worked, (No magisk, safetynet working)

So then ive tried the app on my S7 , with OneUI 2.5 (same base as our N8) and the app also worked (magisk instaled, no magisk hide)

finally, i decided to try it on the note8 with hades Q, the app also worked. (magisk installed, magisk hide enabled, not enabled on the phonepe)

however it is important to mention that i am running a newer version of hadesQ with a kernel bypass for the issue i talked about above, i am not sure its relevant to this bank app or not, all 3 phones had the isolated process workaround enabled in the kernel.

and by "worked" i mean i got the app running to the "enter your mobile number" page, i do not have an indian phone number to test further

**Comment by ankushmalik11201** [comment] 2021-02-08 06:13
Hey thanks for looking into this, the app launches even in my OS too but gave error after entering mobile number. 

Interestingly another app called "Bhim" also have same problem of showing error after entering mobile number. 

To test it I can give you my mobile number if it's possible to privately pm or you can simply replace XXX here with random numbers (it will only send an otp if it works, nothing alarming)

Try this number +917707909733 (It's of receive-sms-online.cc, basically a online burner number for spam / otp signups) or replace the last few digits randomly.

I even tried this ROM without root to see if these app work but it doesn't.

Thanks.

**Comment by ananjaser1211** [comment] 2021-03-08 15:15
i gave this another shot, it fails to register with any of my phones that are not on stock, i looked a bit online, and it seems that this app is notorious with not working on rooted phones. since 2018 (and apps based on it)

our rom is permissive, even when unrooted, it will trigger warnings (and because of oem unlock off) 
and magisk hide is not going to hide everything, your best bet is waiting until magisk hide improves. i will be closing this as it is not something i can fix from the ROM

**Closed as completed by ananjaser1211** 2021-03-08 15:15 UTC
