### ISSUE TITLE
Battery Draining Issue 

### ISSUE THREAD

**Issue by TauqirHassnain** [ananjaser1211/hadesRom_Reports#28] opened 2021-01-01 19:43 UTC
Hi, Thanks for the supporting S8 / N8 Device 👍

I have installed the hadesRom Q v1.0 on my S8 (G950FD) on dated 29th December since install the rom I'm facing the battery draining issue (max 4 hour on screen on)I thought it was battery calibration issue then i calibrated by battery by using this method (https://forum.xda-developers.com/t/guide-how-to-callibrate-battery-on-your-device-root-non-root.3308554/) but it does nothing.

Kindly advice me about better battery health on hadesRom Q v1.0

Device details :

Samsung S8 (G950FD)

**Comment by corsicanu** [comment] 2021-01-01 19:47
Try this:
- at 5% - *#0228# - quick start - ok
- charge to 100%, turn off, turn on, *#0228# - quick start - ok, charge back to 100%
- optional - *#9900# - Batterystats reset

Let me know how it goes.

**Comment by TauqirHassnain** [comment] 2021-01-01 19:48
Let me check this and will update you accordingly. 👍

**Comment by corsicanu** [comment] 2021-01-02 09:44
I'm closing this as it's not a real issue, calibration suggestion from above should give back pie sot values, couldn't reproduce locally as my Note8 pulls 5h+ sot which is a normal value for a 3+ years old device.

**Closed as completed by corsicanu** 2021-01-02 09:44 UTC
Labels: isolated

**Comment by ananjaser1211** [comment] 2021-01-02 14:10
Keep using the rom for a while until it stabilizes more, you will end up with 4~5 hours of SOT, which is to be expected from these phones

**Comment by TauqirHassnain** [comment] 2021-01-11 16:53
Thanks, now battery has stabilized. thumbs up for this Great ROM 👍

**Comment by twinnybloggers** [comment] 2021-02-24 06:53
> Let me check this and will update you accordingly.
Try this, hope this work with you but firstly you must install magisk to rooting hktweaks and following this instruction below :

For those with battery problems I can share my cpu settings in Hktweaks, which for now have reduced the battery drain here they are:
Big frequencies max= 2002mhz
Governor =blu_active (hispeed freq 1469, min semple time 50000)
Little frequencies max= 1456mhz
Governor = blu_active (hispeed freq 1248)
HMP = Battery set.
